version: '3.1'

services:
  fastapi:
    build: ./fastapi
    restart: always
    ports:
      - 80:80
    env_file:
      - .env

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - volume_mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env

  logstash:
    build: ./logstash
    ports:
      - '9600:9600'
      - '514:514'
    env_file:
      - .env
    volumes:
      - ./logstash/logstash.conf:/logstash_dir/logstash.conf
      - volume_logstash:/var/log/docker_logs
    command: logstash -f /logstash_dir/logstash.conf

volumes:
  volume_mongo:
  volume_logstash:
